import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from 'import/styles/Home.module.css'
import MapChart from './MapChart'
import gradientChart from '../data/IncomeScale.png'
import 'react-tooltip/dist/react-tooltip.css'
import Table from 'react-bootstrap/Table'
import Form from 'react-bootstrap/Form'
import Button from 'react-bootstrap/Button'
import mappED from '../data/logo_newbg.png'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const signs1 = ">=100,000";
  const signs2 = "<=10,000";

  return (
    <>
      <Head>
        <title>Housing Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
      <div style={{backgroundColor:"#557153", width:"100%", height:"20px"}}></div>
      <div className='headerBanner'>
        <div style={{backgroundColor:"#285430", height:"10px"}}></div>
        <h2 style={{color:"#F0EBCE", marginLeft:"15px"}}>Find the best county for you!</h2>
        <Table striped bordered hover variant="dark" style={{margin:"10px"}}>
          <thead style={{color:"#F0EBCE"}}>
          <tr>
            <th>State</th>
            <th>Income Level</th>
            <th>Local Education</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td><input type="text"></input></td>
            <td><input type="text"></input></td>
            <td><select><option selected>None</option>
                        <option>Pre School</option>
                        <option>Elementary School</option>
                        <option>Middle School</option>
                        <option>High School</option>
                        <option>College</option>
            </select></td>
            <Button variant="primary" type="submit" style={{color:"#F0EBCE"}}>Search</Button>
          </tr>
          <tr>
            <td></td>
            <td><input type="range"></input></td>
            <td><input type="range"></input></td>
          </tr>
          </tbody>
        </Table>
        <h3 style={{color:"#F0EBCE", margin:"15px"}}>OR</h3>
        <Form style={{color:"#F0EBCE", margin:"15px"}}>
          <Form.Group className="mb-3">
            <Form.Label style={{marginRight:"5px"}}>Search for a County</Form.Label>
            <Form.Control style={{marginRight:"5px"}}/>
            <Button variant="primary" type="submit" style={{color:"#F0EBCE"}}>Search</Button>
          </Form.Group>
          
        </Form>
        <Image src={mappED} className="logo"></Image>
      </div>
      <div style={{backgroundColor:"#A9AF7E", width:"100%", height:"20px"}}></div>
      <main className={styles.main}>
            <MapChart /> 
            <div style={{color: "#22222A", margin:"1%"}}>
              <span style={{display: "flex", justifyContent: "center"}}>Estimate Recommended Yearly Income</span>
              <Image className="gradientChart" src={gradientChart} ></Image>
              <div style={{display:"flex", justifyContent: "space-between", fontSize:"13px"}}>
                <p style={{display:"inline"}}>{signs1}</p><p style={{display:"inline"}}>{signs2}</p>
              </div>
              <span style={{fontSize:"13px", justifyContent:"center", display:"flex"}}>Click on a county for more details!</span>
            </div>
      </main>
    </>
  )
}
